export const UI_DESELECT_SIDENOTE = "UI_DESELECT_SIDENOTE";
export const UI_REPOSITION_SIDENOTES = "UI_REPOSITION_SIDENOTES";
export const UI_CONNECT_SIDENOTE = "UI_CONNECT_SIDENOTE";
export const UI_DISCONNECT_SIDENOTE = "UI_DISCONNECT_SIDENOTE";
export const UI_SELECT_SIDENOTE = "UI_SELECT_SIDENOTE";
export const UI_SELECT_ANCHOR = "UI_SELECT_ANCHOR";
